name: iOS Build
on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        
    - name: Install Cocoapods
      run: |
        gem install cocoapods
        gem install xcpretty
        
    - name: Create Podfile
      run: |
        echo "platform :ios, '16.0'
        target 'WeatherDemo' do
          use_frameworks!
          pod 'GSCXScanner'
        end" > Podfile
        
    - name: Install Dependencies
      run: |
        pod install
        
    - name: Build
      run: |
        xcodebuild -workspace WeatherDemo.xcworkspace -scheme WeatherDemo -configuration Debug build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO IPHONEOS_DEPLOYMENT_TARGET=16.0 | xcpretty --color --simple

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: build/Debug-iphoneos/WeatherDemo.app