name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # 원하는 Ruby 버전 입력

      - name: Install CocoaPods dependencies
        run: |
          gem install cocoapods
          pod install

      - name: Build and run tests
        run: |
          xcodebuild -workspace WeatherDemo.xcworkspace -scheme WeatherDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build test
