name: Build and Test iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ruby for cocoapods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # 사용하려는 루비 버전

      - name: Install dependencies
        run: |
          gem install cocoapods
          pod install

      - name: Build the app and run UI tests
        run: |
          # 빌드 및 UI 테스트 실행 (시뮬레이터 환경에서)
          xcodebuild -workspace WeatherDemo.xcworkspace \
                     -scheme WeatherDemo \
                     -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' \
                     test
          
      - name: Upload test results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: path/to/test-results # 필요에 따라 수정
