name: iOS Build
on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        
    - name: Install Cocoapods
      run: |
        gem install cocoapods
        gem install xcpretty
        
    - name: Create Podfile
      run: |
        echo "platform :ios, '16.0'
        
        target 'WeatherDemo' do
          use_frameworks!
          
          pod 'GSCXScanner'
          pod 'abseil', :modular_headers => true, :inhibit_warnings => true
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              if ['GTXiLib'].include?(target.name)
                target.build_configurations.each do |config|
                  # Use direct header path
                  config.build_settings['HEADER_SEARCH_PATHS'] = [
                    '$(inherited)',
                    '${PODS_ROOT}/**',
                    '${PODS_ROOT}/Headers/Public/abseil/**'
                  ]
                  # Force include path modification
                  config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                  config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABSL_USES_OLD_HEADER_PATH=1'
                  
                  config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
                end
              end
            end
          end
        end" > Podfile
        
    - name: Install Dependencies
      run: |
        pod install --verbose
        
    - name: List Paths
      run: |
        echo "Checking header locations..."
        find ${PODS_ROOT} -name "str_cat.h" || true
        
    - name: Build
      run: |
        xcodebuild -workspace WeatherDemo.xcworkspace -scheme WeatherDemo -configuration Debug build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO IPHONEOS_DEPLOYMENT_TARGET=16.0 | xcpretty --color --simple

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: build/Debug-iphoneos/WeatherDemo.app