name: iOS Build
on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        
    - name: Install Cocoapods
      run: |
        gem install cocoapods
        
    - name: Create Podfile
      run: |
        echo "platform :ios, '13.0'
        target 'WeatherApp' do
          use_frameworks!
          pod 'GSCXScanner'
        end" > Podfile
        
    - name: Install Dependencies
      run: |
        pod install
        
    - name: Build
      run: |
        xcodebuild -workspace WeatherApp.xcworkspace -scheme WeatherApp -configuration Debug build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: build/Debug-iphoneos/WeatherApp.app