name: iOS CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        
    - name: Install CocoaPods
      run: |
        gem install cocoapods
        gem install xcpretty
        
    - name: Pod Install
      run: |
        pod install --verbose
        
    - name: Build and Test
      run: |
        xcodebuild -workspace WeatherDemo.xcworkspace -scheme WeatherDemo -configuration Debug build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO IPHONEOS_DEPLOYMENT_TARGET=16.0 COMPILER_WARNINGS_AS_ERRORS=NO | xcpretty --color --simple

    - name: Find build output
      run: |
        find $PWD -name "WeatherDemo.app"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: |
          $PWD/build/**/*.app
          $PWD/DerivedData/**/*.app