name: iOS Build
on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        
    - name: Install Cocoapods
      run: |
        gem install cocoapods
        gem install xcpretty
        
    - name: Create Podfile
      run: |
        echo "platform :ios, '16.0'  # iOS 버전을 16.0으로 변경
        target 'WeatherDemo' do
          use_frameworks!
          pod 'GSCXScanner'
        end" > Podfile
        
    - name: Install Dependencies
      run: |
        pod install
        
    - name: Build
      run: |
        set -o pipefail && xcodebuild -workspace WeatherDemo.xcworkspace -scheme WeatherDemo -configuration Debug build -verbose CODE_S